[build]
  base = "/"
  functions = "netlify/functions"
  publish = "/"

[build.environment]
  PYTHON_VERSION = "3.10"
# Chatbot Application

Welcome to the Chatbot Application! This project allows you to interact with a chatbot using a Flask web application.

## Setup

### Prerequisites

Before you begin, ensure you have the following installed on your computer:

1. **Python 3.7 or later:** You can download and install it from [python.org](https://www.python.org/downloads/).

2. **Virtual Environment (Optional but recommended):** This helps to create an isolated environment for your project.

### Installation

Follow these steps to set up the Chatbot Application:

1. **Clone the repository:**

    Open your terminal or command prompt and run:

    ```bash
    git clone https://github.com/your-username/chatbot-application.git
    ```

2. **Navigate to the project directory:**

    Change into the project directory:

    ```bash
    cd chatbot
    ```

3. **Create and activate a virtual environment:**

    If you're new to virtual environments, these commands will help set it up:

    ```bash
    python -m venv venv
    ```

    On Windows, use:

    ```bash
    .\venv\Scripts\activate
    ```

    On Unix or MacOS, use:

