[build]
  base = "/"
  functions = "netlify/functions"
  publish = "/"

  command = "source venv/bin/activate && python3 app.py"

[build.environment]
  PYTHON_VERSION = "3.10"
# Chatbot Application


